### ISSUE TITLE
Create a background task to update local cache of sensu alerts

### ISSUE THREAD

**Issue by cryptk** [cryptk/opsy#14]
Currently all data is polled live, we should instead have a background task (likely via a greenlet) that will poll the sensu-api's on a configured interval and store the retrieved data in a local cache (likely using flask-cache).

**Comment by cryptk** [comment]
Background polling and caching of Events, Checks and Clients complete.  There needs to be more resiliency in the system to account for things like slow responding sensu-api nodes, unconnectable api-nodes, etc.

**Comment by testeddoughnut** [comment]
This has been addressed with: #84 #85 #86 #87 #88 and #89 

There needs to be a discussion of what gets cached and what doesn't, for example a request for /results in IAD takes a good 1-2 seconds since its so much data (my sqlite db was 5MiB after it pulled all of it). Caching all of it doesn't really make sense. One option might be to make requests for some of the less-requested data live, then cache the result with a timeout of a minute or so.

The pollers and scheduler probably need to have a go over to add better exception handling. The only thing I have in there at the moment is exception handing for a connection timeout, but it should be handled better.

**Comment by cryptk** [comment]
@testeddoughnut I assigned this one to you since you have been working heavily on it.  Feel free to close it whenever you get the scheduler to a point that you are happy with for v0.1

**Comment by testeddoughnut** [comment]
Going to close this since we have a working scheduler. Will open a new issue for enhancements.
